name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        uses: love2d-community/love-android-action@v1
        with:
          game_path: BombAll.love
          bundle_id: com.klifanik.bomball
          game_name: "Bomb All"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BombAll-APK
          path: "*.apk"
